# OpenROAD Floorplan Script for CXL_3D_Memory_Stack
# Generated by serdes_architect/src/layout/gen_def.py

initialize_floorplan -die_area "0 0 1600.0 1600.0" -core_area "10 10 1590.0 1590.0" -site unithd

place_cell -inst_name Switch_Logic -origin "100.0 100.0" -orient N -status FIRM
place_cell -inst_name Memory_Array -origin "100.0 100.0" -orient N -status FIRM

# Floorplan constraints complete.
