"""Cadence hooks (spec section 3), ordered by effort-to-credibility.

Celsius and Voltus-Fi come first because they check the two headline numbers the
repo advertises: 83.87 C peak Tj (grid-converged) and the 450 A/ns droop event.
"""
from __future__ import annotations

import csv
from pathlib import Path

from ..base import (VendorHook, HookResult, Finding, register, SEV_WARN, SEV_INFO,
                    FIDELITY_SURROGATE, TIER_EMITTED, write_text_with_provenance,
                    provenance_header)
from ..canonical import DesignRecord
from ..interchange import stackup, def_io, touchstone_io as ts

POWER_MAP_CELLS = 16        # 16x16 tiles per die, matching the FNO grid_size


@register
class CelsiusHook(VendorHook):
    """Celsius Thermal Solver: high-fidelity check on the 3D-FDM/FNO prediction.

    Correlation target (T2): peak Tj against the repo's 83.87 C measurement, plus
    hotspot-location agreement.
    """
    vendor, tool = "cadence", "celsius"
    requires = ("dies", "interfaces")

    def emit(self, design: DesignRecord, outdir: Path) -> HookResult:
        prov = self.prov(design)
        files = [stackup.write(design, outdir / "stackup_3dic_x.json", prov).name]

        for die in design.dies:
            path = outdir / f"power_map_{die.name}.csv"
            with open(path, "w", newline="") as fh:
                fh.write(provenance_header(prov, "#"))
                fh.write(f"# 3DIC-X power map for {die.name} -- W per tile, "
                         f"{POWER_MAP_CELLS}x{POWER_MAP_CELLS} tiles\n")
                w = csv.writer(fh)
                w.writerow(["x_um", "y_um", "dx_um", "dy_um", "power_w"])
                dx = die.width_um / POWER_MAP_CELLS
                dy = die.height_um / POWER_MAP_CELLS
                macro_tiles = {(int(m.origin_um[0] // dx), int(m.origin_um[1] // dy))
                               for m in design.macros_on(die.name)}
                n_tiles = POWER_MAP_CELLS ** 2
                # Macro tiles carry 3x the background density (shattered-macro
                # distribution is what recovered the thermal headroom).
                weight_total = n_tiles + 2 * len(macro_tiles)
                tiles = []
                for iy in range(POWER_MAP_CELLS):
                    for ix in range(POWER_MAP_CELLS):
                        wgt = 3.0 if (ix, iy) in macro_tiles else 1.0
                        tiles.append([ix, iy, round(die.power_w * wgt / weight_total, 6)])
                # Conserve power exactly: a thermal deck whose tiles do not sum
                # to the declared die power is a defect, not a rounding detail.
                residual = round(die.power_w - sum(t[2] for t in tiles), 6)
                if tiles:
                    hottest = max(range(len(tiles)), key=lambda i: tiles[i][2])
                    tiles[hottest][2] = round(tiles[hottest][2] + residual, 6)
                for ix, iy, watts in tiles:
                    w.writerow([f"{ix * dx:.3f}", f"{iy * dy:.3f}",
                                f"{dx:.3f}", f"{dy:.3f}", f"{watts:.6f}"])
            files.append(path.name)

        driver = outdir / "run_celsius.tcl"
        write_text_with_provenance(driver, "\n".join([
            "# Celsius Thermal Solver driver -- generated by 3DIC-X",
            "# Requires a Celsius license. This script is not run by CI.",
            f"# design: {design.project}",
            "",
            "set stack [read_json stackup_3dic_x.json]",
            f"set_boundary_condition -case_temp {design.case_temp_c} \\",
            f"    -liquid_flow_lpm {design.liquid_flow_lpm} \\",
            f"    -tim_thickness_um {design.tim_thickness_um}",
            "",
        ] + [f"load_power_map -die {d.name} -file power_map_{d.name}.csv"
             for d in design.dies] + [
            "",
            "# ROI mesh matches physics_accelerated/src/hierarchical_grid_manager.py",
            "set_mesh -global_um 1.0 -roi_um 0.05",
            "solve_thermal -steady_state",
            "report_temperature -format csv -file celsius_temperature.csv",
            "",
            "# Hand celsius_temperature.csv back with:",
            "#   python -m integrations.cli correlate --thermal celsius_temperature.csv",
        ]), prov, "#")
        files.append(driver.name)

        return HookResult(self.vendor, self.tool, self.tier, self.fidelity, files=files,
                          driver=driver.name,
                          notes=[f"correlation target: peak Tj vs surrogate "
                                 f"{design.predictions.tj_peak_c} C",
                                 f"stack dissipates {design.total_power_w():.1f} W"])

    def validate(self, design, result, outdir):
        f = super().validate(design, result, outdir)
        f += stackup.validate(stackup.read(outdir / "stackup_3dic_x.json"))
        for die in design.dies:
            path = outdir / f"power_map_{die.name}.csv"
            if not path.exists():
                continue
            rows = [r for r in csv.DictReader(
                ln for ln in path.read_text().splitlines() if not ln.startswith("#"))]
            total = sum(float(r["power_w"]) for r in rows)
            if abs(total - die.power_w) > max(1e-6, die.power_w * 1e-6):
                f.append(Finding("error", "power_conservation",
                                 f"{die.name} power map sums to {total:.6f} W != "
                                 f"{die.power_w} W"))
            elif len(rows) != POWER_MAP_CELLS ** 2:
                f.append(Finding(SEV_WARN, "power_map_size",
                                 f"{die.name} has {len(rows)} tiles"))
            else:
                f.append(Finding(SEV_INFO, "power_conservation",
                                 f"{die.name}: {len(rows)} tiles summing to {total:.3f} W"))
        f.append(Finding(SEV_WARN, "tier",
                         "T1/T2 require a Celsius license; this run emits only (T0)"))
        return f


@register
class VoltusFiHook(VendorHook):
    """Voltus-Fi: golden check on the FNO's IR-drop/droop prediction."""
    vendor, tool = "cadence", "voltus_fi"
    requires = ("dies", "stripes", "nets")

    def emit(self, design: DesignRecord, outdir: Path) -> HookResult:
        prov = self.prov(design)
        files = []
        for die in design.dies:
            if design.macros_on(die.name):
                files.append(def_io.write(design, die, outdir / f"{die.name}.def", prov).name)

        # di/dt event from electrical_noise_deck: 450 A/ns ramp then decay.
        prof = outdir / "current_profile.csv"
        peak_a = design.total_power_w() / max(design.vddq_v, 1e-9)
        ramp_ns = peak_a / design.didt_a_per_ns
        with open(prof, "w", newline="") as fh:
            fh.write(provenance_header(prov, "#"))
            fh.write(f"# di/dt event: {design.didt_a_per_ns} A/ns to "
                     f"{peak_a:.1f} A peak\n")
            w = csv.writer(fh)
            w.writerow(["time_ns", "current_a"])
            for i in range(41):
                t = i * ramp_ns / 8.0
                i_a = (design.didt_a_per_ns * t if t <= ramp_ns
                       else peak_a * pow(0.85, (t - ramp_ns) / max(ramp_ns, 1e-9)))
                w.writerow([f"{t:.6f}", f"{min(i_a, peak_a):.4f}"])
        files.append(prof.name)

        vert = outdir / "vertical_pdn.spice"
        lines = ["* Vertical PDN: power die -> logic through TSV / hybrid bond",
                 f"* nominal {design.vddq_v} V, ripple target {design.ripple_target_mv} mV"]
        for net in design.nets:
            if net.kind in ("vertical", "pdn_trunk"):
                lines += [f"R_{net.name} n_{net.name}_in n_{net.name}_out {net.r_ohm:.6g}",
                          f"C_{net.name} n_{net.name}_out 0 {net.c_pf:.6g}p"]
        vert.write_text("\n".join(lines) + "\n")
        files.append(vert.name)

        driver = outdir / "run_voltus_fi.tcl"
        write_text_with_provenance(driver, "\n".join([
            "# Voltus-Fi driver -- generated by 3DIC-X. Requires a Voltus license.",
            f"set_power_budget {design.total_power_w():.3f}",
            f"set_nominal_voltage {design.vddq_v}",
            "read_def " + " ".join(f"{d.name}.def" for d in design.dies
                                   if design.macros_on(d.name)),
            "read_spice vertical_pdn.spice",
            "read_current_profile current_profile.csv",
            "analyze_rail -dynamic -vectorless",
            "report_ir_drop -format csv -file voltus_ir_drop.csv",
            "",
            "# Hand voltus_ir_drop.csv back with:",
            "#   python -m integrations.cli correlate --ir voltus_ir_drop.csv",
        ]), prov, "#")
        files.append(driver.name)

        return HookResult(self.vendor, self.tool, self.tier, self.fidelity, files=files,
                          driver=driver.name,
                          notes=[f"correlation target: worst droop vs surrogate "
                                 f"{design.predictions.droop_mv:.2f} mV"
                                 if design.predictions.droop_mv else "no droop prediction",
                                 f"peak current {peak_a:.1f} A, ramp {ramp_ns:.3f} ns"])

    def validate(self, design, result, outdir):
        f = super().validate(design, result, outdir)
        for die in design.dies:
            path = outdir / f"{die.name}.def"
            if path.exists():
                f += def_io.validate(def_io.read(path), die, design.macros_on(die.name))
        prof = outdir / "current_profile.csv"
        if prof.exists():
            rows = [r for r in csv.DictReader(
                ln for ln in prof.read_text().splitlines() if not ln.startswith("#"))]
            ts_ = [float(r["time_ns"]) for r in rows]
            cs = [float(r["current_a"]) for r in rows]
            slopes = [(cs[i + 1] - cs[i]) / (ts_[i + 1] - ts_[i])
                      for i in range(len(rows) - 1) if ts_[i + 1] > ts_[i]]
            worst = max(slopes) if slopes else 0.0
            if worst > design.didt_a_per_ns * 1.001:
                f.append(Finding("error", "didt",
                                 f"profile slope {worst:.1f} A/ns exceeds the declared "
                                 f"{design.didt_a_per_ns} A/ns"))
            else:
                f.append(Finding(SEV_INFO, "didt",
                                 f"max slope {worst:.1f} A/ns within the declared "
                                 f"{design.didt_a_per_ns} A/ns"))
        f.append(Finding(SEV_WARN, "tier", "T1/T2 require a Voltus license (T0 here)"))
        return f


@register
class SigrityHook(VendorHook):
    """Sigrity / EDB stackup + ports: the field-solved source that eventually
    replaces the SYNTHETIC Touchstone (spec 3.3)."""
    vendor, tool = "cadence", "sigrity_edb"
    requires = ("dies", "links")

    def emit(self, design: DesignRecord, outdir: Path) -> HookResult:
        prov = self.prov(design)
        files = [stackup.write(design, outdir / "stackup_3dic_x.json", prov).name]
        ports = outdir / "port_definitions.csv"
        with open(ports, "w", newline="") as fh:
            fh.write(provenance_header(prov, "#"))
            fh.write("# port order must match the .s4p: 1,2 = TX P/N; 3,4 = RX P/N\n")
            w = csv.writer(fh)
            w.writerow(["link", "port", "role", "net", "z0_ohm", "reference"])
            for link in design.links:
                for idx, (role, net) in enumerate(
                        [("TX_P", f"{link.name}_TX_P"), ("TX_N", f"{link.name}_TX_N"),
                         ("RX_P", f"{link.name}_RX_P"), ("RX_N", f"{link.name}_RX_N")], 1):
                    w.writerow([link.name, idx, role, net, link.z0_ohm, "VSS"])
        files.append(ports.name)

        script = outdir / "build_edb.py"
        write_text_with_provenance(script, '\n'.join([
            '"""Sigrity/EDB build script -- generated by 3DIC-X.',
            '',
            'EDB is a database, not a text format, so this scripts against PyEDB',
            'rather than emitting a file (spec 3.3).  Requires a Cadence install.',
            '"""',
            'import csv, json',
            '',
            'stack = json.load(open("stackup_3dic_x.json"))',
            'assert stack["units"]["length"] == "um"',
            '',
            '# from pyedb import Edb          # requires the vendor install',
            '# edb = Edb(edbversion="2026.1")',
            'for die in stack["dies"]:',
            '    print("add layer", die["name"], die["thickness_um"], "um")',
            'for iface in stack["interfaces"]:',
            '    print("add interface", iface["type"], iface["pitch_um"], "um pitch")',
            'for row in csv.DictReader(l for l in open("port_definitions.csv")',
            '                          if not l.startswith("#")):',
            '    print("create port", row["link"], row["port"], row["role"])',
            '',
            '# Export the field-solved result, then correlate:',
            '#   python -m integrations.cli correlate --sparam <link>.s4p --link LINK_0',
        ]), prov, "#")
        files.append(script.name)
        return HookResult(self.vendor, self.tool, self.tier, self.fidelity, files=files,
                          driver=script.name,
                          notes=["upgrades the channel model from SYNTHETIC to "
                                 "FIELD_SOLVED once run (spec 2.6 step 2)"])

    def validate(self, design, result, outdir):
        f = super().validate(design, result, outdir)
        f += stackup.validate(stackup.read(outdir / "stackup_3dic_x.json"))
        rows = list(csv.DictReader(
            ln for ln in (outdir / "port_definitions.csv").read_text().splitlines()
            if not ln.startswith("#")))
        if len(rows) != 4 * len(design.links):
            f.append(Finding("error", "ports",
                             f"{len(rows)} ports for {len(design.links)} links "
                             "(expected 4 per link)"))
        f.append(Finding(SEV_WARN, "tier", "T1 requires a Sigrity license (T0 here)"))
        return f
