"""Siemens EDA hooks (spec section 5).

Recorded deliberately: resume positioning keeps Mentor at legacy DRC/LVS, and
that stands.  The repo is a separate question -- Calibre 3DSTACK is the
industry-standard multi-die assembly check, and 3DIC-X currently has no LVS at
all, so leaving Siemens out is a real technical gap.
"""
from __future__ import annotations

import json
from pathlib import Path

from ..base import (VendorHook, HookResult, Finding, register, SEV_WARN, SEV_INFO,
                    FIDELITY_SYNTHETIC, write_text_with_provenance)
from ..canonical import DesignRecord
from ..interchange import gds_io, stackup, touchstone_io as ts, ibis_io


@register
class Calibre3dStackHook(VendorHook):
    """Calibre 3DSTACK: stack-level assembly + LVS -- the gap-closer.

    3DIC-X asserts 4.2 TB/s over a 5um hybrid-bond interface.  This is where
    'the bonds land where we said' becomes checkable; gds_export.tcl had
    check_lvs commented out, so the repo has no LVS today.
    """
    vendor, tool = "siemens", "calibre_3dstack"
    requires = ("dies", "interfaces", "macros")

    def emit(self, design: DesignRecord, outdir: Path) -> HookResult:
        prov = self.prov(design)
        files = []
        for die in design.dies:
            if design.macros_on(die.name):
                p = gds_io.write(design, die, outdir / f"{die.name}.gds", prov)
                files += [p.name, p.name + ".provenance.json"]
        files.append(stackup.write(design, outdir / "stackup_3dic_x.json", prov).name)

        # Assembly description: die z-order, placement, rotation, bond interface.
        asm = outdir / "assembly.json"
        z = 0.0
        entries = []
        for die in design.dies:
            entries.append({"die": die.name,
                            "gds": f"{die.name}.gds" if design.macros_on(die.name) else None,
                            "top_cell": die.name.upper()[:31],
                            "placement_um": [0.0, 0.0],
                            "rotation_deg": 0,
                            "z_bottom_um": round(z, 3),
                            "z_top_um": round(z + die.thickness_um, 3),
                            "face": "down" if die.bspdn else "up"})
            z += die.thickness_um
        asm.write_text(json.dumps({
            "provenance": prov,
            "design": design.project,
            "units": {"length": "um"},
            "stack": entries,
            "interfaces": [{"between": list(i.between), "type": i.kind,
                            "pitch_um": i.pitch_um, "diameter_um": i.diameter_um}
                           for i in design.interfaces],
        }, indent=2) + "\n")
        files.append(asm.name)

        runset = outdir / "calibre_3dstack.rule"
        write_text_with_provenance(runset, "\n".join([
            "// Calibre 3DSTACK runset -- generated by 3DIC-X",
            "// Requires Calibre; not run by CI.",
            f"// design: {design.project}",
            "",
            "LAYOUT SYSTEM GDSII",
        ] + [f'LAYOUT PATH "{d.name}.gds"' for d in design.dies
             if design.macros_on(d.name)] + [
            "",
            "// Stack assembly comes from assembly.json (die order, z, rotation).",
            "STACK ASSEMBLY FILE \"assembly.json\"",
            "",
            "// Connectivity expectations for the 3D interfaces:",
        ] + [f"//   {i.between[0]} <-> {i.between[1]}: {i.kind} at {i.pitch_um} um pitch"
             for i in design.interfaces] + [
            "",
            f"LAYER BOND {gds_io.LAYER_BOND}",
            f"LAYER TSV  {gds_io.LAYER_TSV}",
            "",
            "// Stack-level LVS: compare bond/TSV connectivity to the source netlists.",
            "LVS REPORT \"calibre_3dstack_lvs.rpt\"",
            "DRC RESULTS DATABASE \"calibre_3dstack_drc.db\"",
        ]), prov, "//")
        files.append(runset.name)

        return HookResult(self.vendor, self.tool, self.tier, self.fidelity, files=files,
                          driver=runset.name,
                          notes=[f"{len(entries)} dies, total stack height "
                                 f"{z:.1f} um",
                                 "the only LVS path in this repo"])

    def validate(self, design, result, outdir):
        f = super().validate(design, result, outdir)
        for die in design.dies:
            path = outdir / f"{die.name}.gds"
            if path.exists():
                f += gds_io.validate(gds_io.read(path), design, die)
        asm = json.loads((outdir / "assembly.json").read_text())
        z_prev = None
        for entry in asm["stack"]:
            if z_prev is not None and abs(entry["z_bottom_um"] - z_prev) > 1e-6:
                f.append(Finding("error", "stack_gap",
                                 f"{entry['die']} starts at {entry['z_bottom_um']} um "
                                 f"but the die below ends at {z_prev} um"))
            z_prev = entry["z_top_um"]
        names = {e["die"] for e in asm["stack"]}
        for iface in asm["interfaces"]:
            for side in iface["between"]:
                if side not in names and side != "package":
                    f.append(Finding("error", "interface_ref",
                                     f"interface references unknown die '{side}'"))
        f.append(Finding(SEV_INFO, "stack",
                         f"{len(asm['stack'])} dies, contiguous z from 0 to {z_prev} um"))
        f.append(Finding(SEV_WARN, "tier", "T1 requires a Calibre license (T0 here)"))
        return f


@register
class HyperLynxHook(VendorHook):
    """HyperLynx: independent SI/PI check. Consumes Touchstone + IBIS directly,
    so Phase 0 nearly finishes this hook -- the cheapest T1 in the plan."""
    vendor, tool = "siemens", "hyperlynx"
    fidelity = FIDELITY_SYNTHETIC
    requires = ("links", "dies")

    def emit(self, design: DesignRecord, outdir: Path) -> HookResult:
        prov = self.prov(design)
        files = [stackup.write(design, outdir / "stackup_3dic_x.json", prov).name]
        for link in design.links:
            files.append(ts.write(link, outdir / f"{link.name}.s4p", prov).name)
        link0 = design.links[0]
        files.append(ibis_io.write_ibs(design, link0, outdir / f"{link0.name}.ibs", prov).name)
        files.append(ibis_io.write_ami(design, link0, outdir / f"{link0.name}.ami", prov).name)

        driver = outdir / "run_hyperlynx.txt"
        write_text_with_provenance(driver, "\n".join([
            "HyperLynx setup -- generated by 3DIC-X. Requires a HyperLynx license.",
            f"design: {design.project}",
            "",
            "1. Import stackup_3dic_x.json (units are um; verify on import).",
            "2. Attach the per-link S-parameters:",
        ] + [f"     {l.name}: {l.name}.s4p  (ports 1,2 = TX P/N; 3,4 = RX P/N)"
             for l in design.links] + [
            f"3. Attach the buffer model {link0.name}.ibs with {link0.name}.ami "
            "(Init-only; no GetWave DLL).",
            "4. Run the eye analysis and export the eye height/width.",
            "",
            "Correlation targets (spec 5.2):",
            f"  eye margin      surrogate {design.predictions.eye_margin_ui} UI",
            f"  insertion loss  surrogate {design.predictions.insertion_loss_db:.2f} dB"
            if design.predictions.insertion_loss_db is not None else "  insertion loss  n/a",
            f"  worst droop     surrogate {design.predictions.droop_mv:.2f} mV"
            if design.predictions.droop_mv is not None else "  worst droop     n/a",
            "",
            "Hand the exported .s4p back with:",
            f"  python -m integrations.cli correlate --sparam <exported>.s4p --link {link0.name}",
        ]), prov, "#")
        files.append(driver.name)
        return HookResult(self.vendor, self.tool, self.tier, self.fidelity, files=files,
                          driver=driver.name,
                          notes=["consumes Phase 0 artifacts unchanged -- cheapest T1"])

    def validate(self, design, result, outdir):
        f = super().validate(design, result, outdir)
        f += stackup.validate(stackup.read(outdir / "stackup_3dic_x.json"))
        for link in design.links:
            path = outdir / f"{link.name}.s4p"
            if path.exists():
                freqs, s, _ = ts.read(path)
                f += ts.validate(freqs, s, link)
        ibs = outdir / f"{design.links[0].name}.ibs"
        if ibs.exists():
            f += ibis_io.validate(ibis_io.read_ibs(ibs))
        f.append(Finding(SEV_WARN, "tier", "T1 requires a HyperLynx license (T0 here)"))
        return f
