"""Synopsys hooks (spec section 4)."""
from __future__ import annotations

import csv
import glob
import json
from pathlib import Path

from ..base import (VendorHook, HookResult, Finding, register, REPO_ROOT,
                    SEV_WARN, SEV_INFO, FIDELITY_SYNTHETIC,
                    write_text_with_provenance)
from ..canonical import DesignRecord
from ..interchange import touchstone_io as ts, spice_io, spef_io


@register
class PrimeSimHook(VendorHook):
    """PrimeSim HSPICE/XA: the 'physical -> SPICE' leg of the flow claim.

    Emits both the vendor deck (Touchstone channel) and the ngspice-runnable
    equivalent, so the topology is proven to simulate before anyone spends a
    PrimeSim license on it.
    """
    vendor, tool = "synopsys", "primesim"
    fidelity = FIDELITY_SYNTHETIC       # channel comes from the analytic budget
    requires = ("links", "nets")

    def emit(self, design: DesignRecord, outdir: Path) -> HookResult:
        prov = self.prov(design)
        files, notes = [], []
        for link in design.links[:1]:
            s4p = ts.write(link, outdir / f"{link.name}.s4p", prov)
            files.append(s4p.name)
            files.append(spice_io.write_primesim(design, link,
                                                 outdir / f"{link.name}_primesim.sp",
                                                 prov, s4p.name).name)
            files.append(spice_io.write_ngspice(design, link,
                                                outdir / f"{link.name}_ngspice.sp",
                                                prov).name)
            notes.append(f"{link.name}: {link.rate_gbps:g}G {link.modulation} over "
                         f"{link.reach_mm} mm {link.material}")
        driver = outdir / "run_primesim.sh"
        write_text_with_provenance(driver, "\n".join([
            "#!/bin/sh",
            "# PrimeSim driver -- generated by 3DIC-X. Requires a PrimeSim license.",
            "set -e",
            f'primesim -spice {design.links[0].name}_primesim.sp -o primesim_out',
            "# Then correlate the eye against the surrogate:",
            "#   python -m integrations.cli correlate --sparam <field_solved>.s4p --link "
            f"{design.links[0].name}",
        ]), prov, "#")
        driver.chmod(0o755)
        files.append(driver.name)
        return HookResult(self.vendor, self.tool, self.tier, self.fidelity, files=files,
                          driver=driver.name, notes=notes)

    def validate(self, design, result, outdir):
        f = super().validate(design, result, outdir)
        for link in design.links[:1]:
            s4p = outdir / f"{link.name}.s4p"
            if s4p.exists():
                freqs, s, _ = ts.read(s4p)
                f += ts.validate(freqs, s, link)
            ng = outdir / f"{link.name}_ngspice.sp"
            if ng.exists():
                f += spice_io.validate(spice_io.run_ngspice(ng), link, design)
            ps = outdir / f"{link.name}_primesim.sp"
            if ps.exists():
                text = ps.read_text()
                if f"tstonefile='{link.name}.s4p'" not in text:
                    f.append(Finding("error", "primesim_channel",
                                     "deck does not reference the emitted Touchstone file"))
                if ".temp" not in text:
                    f.append(Finding(SEV_WARN, "primesim_temp",
                                     "no ROI temperature injection in the deck"))
        f.append(Finding(SEV_WARN, "tier", "T1 requires a PrimeSim license (T0 here)"))
        return f


@register
class StarRcHook(VendorHook):
    """StarRC: makes the surrogate's training parasitics defensible (spec 4.2).

    Ships the analytic SPEF alongside the run script so the returned golden SPEF
    can be diffed net-by-net.
    """
    vendor, tool = "synopsys", "starrc"
    requires = ("nets",)

    def emit(self, design: DesignRecord, outdir: Path) -> HookResult:
        prov = self.prov(design)
        files = [spef_io.write(design, outdir / "3dic_x_analytic.spef", prov).name]
        cmd = outdir / "starrc.cmd"
        write_text_with_provenance(cmd, "\n".join([
            "* StarRC command file -- generated by 3DIC-X",
            "* Requires StarRC and a foundry ITF/NXTGRD; neither ships with this repo.",
            "BLOCK: " + design.project.replace(" ", "_"),
            "MILKYWAY_DATABASE: ./mw_lib",
            "TCAD_GRD_FILE: <foundry>/3nm_gaa.nxtgrd",
            "MAPPING_FILE: <foundry>/3nm_gaa.map",
            "NETLIST_FORMAT: SPEF",
            "NETLIST_FILE: starrc_golden.spef",
            "REDUCTION: YES",
            "COUPLING_CAP_THRESHOLD: 0.01",
            f"OPERATING_TEMPERATURE: {design.op_temp_c}",
            "",
            "* Diff the golden SPEF against the analytic one:",
            "*   python -m integrations.cli correlate --spef starrc_golden.spef",
        ]), prov, "*")
        files.append(cmd.name)
        harness = outdir / "compare_spef.sh"
        write_text_with_provenance(harness, "\n".join([
            "#!/bin/sh",
            "# Per-net R/C error distribution: analytic surrogate vs StarRC golden.",
            "set -e",
            'test -f starrc_golden.spef || { echo "run StarRC first"; exit 1; }',
            "python -m integrations.cli correlate --spef starrc_golden.spef",
            "# Retrain the surrogate on the golden values (spec 4.2):",
            "#   configs/surrogate_calibration.json now carries rc_scale_by_class",
        ]), prov, "#")
        harness.chmod(0o755)
        files.append(harness.name)
        return HookResult(self.vendor, self.tool, self.tier, self.fidelity, files=files,
                          driver=cmd.name,
                          notes=[f"{len(design.nets)} modeled nets to diff",
                                 "closes the loop that currently trains physics on heuristics"])

    def validate(self, design, result, outdir):
        f = super().validate(design, result, outdir)
        f += spef_io.validate(spef_io.read(outdir / "3dic_x_analytic.spef"), design)
        f.append(Finding(SEV_WARN, "tier", "T2 requires a StarRC license + foundry ITF (T0 here)"))
        return f


@register
class PrimeWaveHook(VendorHook):
    """PrimeWave Design Environment as the sweep driver, replacing the bash
    loops over configs/sweep_*.json (spec 4.3)."""
    vendor, tool = "synopsys", "primewave"
    requires = ("links",)

    def emit(self, design: DesignRecord, outdir: Path) -> HookResult:
        sweeps = sorted(glob.glob(str(REPO_ROOT / "configs/sweep_*.json")))
        axes: dict[str, set] = {}
        points = []
        for path in sweeps:
            try:
                cfg = json.loads(Path(path).read_text())
            except Exception:
                continue
            cons = cfg.get("constraints", {})
            point = {
                "name": Path(path).stem,
                "rate_gbps": cfg.get("target_bandwidth_gbps"),
                "modulation": cons.get("modulation"),
                "clock_mode": cons.get("clock_mode"),
                "fec": cons.get("fec_preference"),
                "reach_mm": cfg.get("reach_mm"),
            }
            points.append(point)
            for k, v in point.items():
                if k != "name" and v is not None:
                    axes.setdefault(k, set()).add(v)

        plan = outdir / "primewave_sweep_plan.json"
        plan.write_text(json.dumps({
            "provenance": self.prov(design),
            "design": design.project,
            "corners": {"temperature_c": [25.0, design.op_temp_c, 110.0],
                        "voltage_v": [design.vdd_v, design.vddq_v],
                        "process": ["typ", "ff", "ss"]},
            "axes": {k: sorted(v, key=str) for k, v in axes.items()},
            "points": points,
            "source": "configs/sweep_*.json",
        }, indent=2) + "\n")

        tcl = outdir / "primewave_setup.tcl"
        write_text_with_provenance(tcl, "\n".join([
            "# PrimeWave sweep setup -- generated by 3DIC-X from configs/sweep_*.json",
            "# Requires PrimeWave.",
            f"set_design {design.project}",
            f"add_corner -name hot -temp {design.op_temp_c} -voltage {design.vdd_v}",
            "add_corner -name nom -temp 25.0 -voltage " + f"{design.vddq_v}",
            f"# {len(points)} sweep points, {len(axes)} axes",
            "read_sweep_plan primewave_sweep_plan.json",
            "run_sweep -distribute",
        ]), self.prov(design), "#")
        return HookResult(self.vendor, self.tool, self.tier, self.fidelity,
                          files=[plan.name, tcl.name], driver=tcl.name,
                          notes=[f"{len(points)} sweep points harvested from "
                                 f"{len(sweeps)} config files"])

    def validate(self, design, result, outdir):
        f = super().validate(design, result, outdir)
        doc = json.loads((outdir / "primewave_sweep_plan.json").read_text())
        if not doc["points"]:
            f.append(Finding(SEV_WARN, "sweep_empty",
                             "no configs/sweep_*.json found to build a plan from"))
        else:
            f.append(Finding(SEV_INFO, "sweep",
                             f"{len(doc['points'])} points across axes "
                             f"{sorted(doc['axes'])}"))
        f.append(Finding(SEV_WARN, "tier", "T1 requires a PrimeWave license (T0 here)"))
        return f
