import argparse
import json
import os

def generate_def(args):
    print(f"🏗️ Generating OpenROAD Floorplan from {args.golden_config}...")
    
    # Load Golden Config
    with open(args.golden_config, 'r') as f:
        config = json.load(f)
        
    project_name = config.get('project_name', 'Unknown_Project')
    die_hierarchy = config.get('die_hierarchy', {})
    
    # Extract Floorplan Data from GEPA Results
    # GEPA output structure: 'floorplan': {'die_0_placement': [x, y], ...}
    floorplan = config.get('floorplan', {})
    
    # Define Tcl Output Path
    output_tcl = 'scripts/floorplan.tcl'
    os.makedirs(os.path.dirname(output_tcl), exist_ok=True)
    
    with open(output_tcl, 'w') as f:
        f.write(f"# OpenROAD Floorplan Script for {project_name}\n")
        f.write("# Generated by serdes_architect/src/layout/gen_def.py\n\n")
        
        # 1. Initialize Floorplan
        # Assuming grid_size 16 maps to physical dimensions (e.g., 1600um x 1600um)
        # Using a simple scaling factor: 1 grid unit = 100 microns
        scale = 100.0 
        die_width = 16 * scale
        die_height = 16 * scale
        
        f.write(f"initialize_floorplan -die_area \"0 0 {die_width} {die_height}\" -core_area \"10 10 {die_width-10} {die_height-10}\" -site unithd\n\n")
        
        # 2. Place Macros (Dies as Macros in a top-level context)
        # In a real 3D flow, this might be separate runs for each die, or a multi-die tech LEF.
        # Here we treat them as macros on a single interposer canvas for visualization.
        
        # Logic Die (Die 0)
        if 'die_0' in die_hierarchy:
            pos = floorplan.get('die_0_placement', [0, 0])
            x, y = pos[0] * scale, pos[1] * scale
            w, h = 400.0, 400.0 # Fixed size 4x4 grid units for demo
            name = die_hierarchy['die_0']['name']
            f.write(f"place_cell -inst_name {name} -origin \"{x} {y}\" -orient N -status FIRM\n")
            
        # Memory Die (Die 1)
        if 'die_1' in die_hierarchy:
            pos = floorplan.get('die_1_placement', [8, 8])
            x, y = pos[0] * scale, pos[1] * scale
            w, h = 400.0, 400.0
            name = die_hierarchy['die_1']['name']
            f.write(f"place_cell -inst_name {name} -origin \"{x} {y}\" -orient N -status FIRM\n")
            
        f.write("\n# Floorplan constraints complete.\n")
        
    print(f"  ✅ generated {output_tcl}")
    print("  Ready for 'openroad -no_gui scripts/place_and_route.tcl'")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--golden_config', type=str, required=True, help='Path to optimized config JSON')
    args = parser.parse_args()
    
    generate_def(args)
