import json
import os
import argparse

class SmartNetlistExporter:
    def __init__(self, config_path):
        with open(config_path, 'r') as f:
            self.config = json.load(f)
        
        self.floorplan = self.config.get('floorplan', {})
        self.temp_map = self.config.get('estimated_max_temp', 25.0) # Simplified
        self.ir_droop = self.config.get('ir_drop_signoff', {}).get('droop_percentage', 0.0)

    def export_smart_deck(self, output_path="results/top_smart.sp"):
        print(f"🧩 Exporting Smart Simulation Deck: {output_path}...")
        
        lines = []
        lines.append("* Smart Simulation Deck for " + self.config.get('project_name', 'Unknown'))
        lines.append("* Generated by Autonomous Architect (Enterprise Mode)")
        lines.append("\n.PARAM VDD_NOM=0.8")
        
        # 1. ROI Identification (Hotspots)
        # We keep SerDes clusters and Logic hotspots in high detail
        lines.append("\n* --- REGION OF INTEREST (ROI): HIGH DETAIL ---")
        for i in range(8):
            local_t = self.temp_map + (i * 0.5) # Slight spatial variance
            local_v = 0.8 * (1.0 - (self.ir_droop/100.0))
            lines.append(f"XSERDES_N_{i} TX_IN_N{i} TX_OUT_N{i} SERDES_LANE .TEMP={local_t:.1f} .VDD={local_v:.3f}")
            
        # 2. Quiet Zones (Pruned / Lumped)
        lines.append("\n* --- QUIET ZONES: LUMPED MODELS ---")
        lines.append("XCORE_QUIET CORE_INPUT CORE_OUTPUT COMPACT_CORE_MODEL .TEMP=45.0 .VDD=0.79")
        
        # 3. Controlled Impedance (CILD)
        lines.append("\n* --- CILD: CONTROLLED IMPEDANCE LINES ---")
        lines.append("W_LINK1 RX_IN TX_OUT TLINE_MODEL L=300m")
        
        # 4. Netlist Annotation
        lines.append("\n.MODEL SERDES_LANE PMOS (LEVEL=54 ...)")
        lines.append(".MODEL COMPACT_CORE_MODEL R=100 C=10p")
        
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, 'w') as f:
            f.write("\n".join(lines))
            
        print(f"  ✅ Smart Netlist generated with .TEMP and .VDD annotations.")
        return output_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', type=str, required=True)
    args = parser.parse_args()
    exporter = SmartNetlistExporter(args.config)
    exporter.export_smart_deck()
